# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingTrips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('retailer', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=20)),
                ('item_spend', models.FloatField()),
                ('item_units', models.IntegerField()),
            ],
        ),
    ]
