# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0002_auto_20171111_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingtrips',
            name='id',
        ),
        migrations.AlterField(
            model_name='shoppingtrips',
            name='trip_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
