# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0006_auto_20171111_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingTrips',
            new_name='Trips',
        ),
    ]
