# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis_app', '0008_delete_trips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_id', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('retailer', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=20)),
                ('item_spend', models.IntegerField()),
                ('item_units', models.IntegerField()),
            ],
        ),
    ]
